apiVersion: v2
name: gitops-helm
description: Install a Nho Luong GitOps Agent - for more information, please visit https://github.com/nholuongut/gitops-istio.
version: 1.1.10
dependencies:
  - name: argo-cd
    version: 6.7.18
    repository: https://argoproj.github.io/argo-helm
    condition: argo-cd.enabled
