{{- if .Values.nholuongut.networkPolicy.create }}
{{- $argo := (index .Values "argo-cd") -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    {{- include "nholuongut.labels" (dict "context" . "component" .Values.repoServer.name "name" .Values.repoServer.name) | nindent 4 }}
  name: {{ template "argo-cd.repoServer.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "nholuongut.agentSelectorLabels" (dict "context" . "name" .Values.agent.name) | nindent 10 }}
    - podSelector:
        matchLabels:
          {{- include "nholuongut.selectorLabels" (dict "context" . "name" .Values.controller.name) | nindent 10 }}
    {{- if $argo.applicationSet.enabled }}
    - podSelector:
        matchLabels:
          {{- include "nholuongut.selectorLabels" (dict "context" . "name" .Values.applicationSet.name) | nindent 10 }}
    {{- end }}
    ports:
    - port: repo-server
      protocol: TCP
  {{- if $argo.repoServer.metrics.enabled }}
  - from:
    - namespaceSelector: {}
    ports:
    - port: metrics
  {{- end }}
  podSelector:
    matchLabels:
      {{- include "nholuongut.selectorLabels" (dict "context" . "name" .Values.repoServer.name) | nindent 6 }}
  policyTypes:
  - Ingress
{{- end }}
